#!/bin/bash

set -eE

. /org/wanna-build/triggers/common

SUITE="$1"
ARCH="$2"
SOURCES_BASE="$3"
PACKAGES_BASE="$4"
SOURCES="$5"
PACKAGES="$6"
WB_SUITE="$7"
WHITELIST_FILE="$8"

new-keep-latest ${ARCH} $(eval echo $(echo ${PACKAGES} | sed -e 's/%ARCH%/${ARCH}/g')) > Packages.${SUITE}.${ARCH}
new-keep-latest ${ARCH} Packages.${SUITE}.${ARCH} $(eval echo $(echo ${PACKAGES_BASE} | sed -e 's/%ARCH%/${ARCH}/g')) > Packages.${SUITE}.${ARCH}-all
do_quinn ${SUITE} ${ARCH} "${WHITELIST_FILE}"
do_wb_merge_all ${SUITE} ${ARCH} ${WB_SUITE} overlay

