#!/bin/bash -x

set -eE

. /org/wanna-build/triggers/common

SUITE="$1"
ARCH="$2"
PACKAGES_BASE="$3"
SOURCES="$4"
PACKAGES="$5"
WB_SUITE="$6"
WHITELIST_FILE="$7"

new-keep-latest ${ARCH} $(eval echo $(echo ${PACKAGES} | sed -e 's/%ARCH%/${ARCH}/g')) > Packages.${SUITE}.${ARCH}
rm Packages.${SUITE}.${ARCH}-all
for FILE in Packages.${SUITE}.${ARCH} $(eval echo $(echo ${PACKAGES_BASE} | sed -e 's/%ARCH%/${ARCH}/g')); do
	case $FILE in
		*.gz)
			gzip -dc < $FILE >> Packages.${SUITE}.${ARCH}-all
			;;
		*)   
			cat < $FILE >> Packages.${SUITE}.${ARCH}-all
			;;
	esac
done
do_quinn ${SUITE} ${ARCH} "${WHITELIST_FILE}"
do_wb_merge_all ${SUITE} ${ARCH} ${WB_SUITE} secondary

