Document: wanna-build
Title: Debian wanna-build Manual
Author: <insert document author here>
Abstract: This manual describes what wanna-build is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wanna-build/wanna-build.sgml.gz

Format: postscript
Files: /usr/share/doc/wanna-build/wanna-build.ps.gz

Format: text
Files: /usr/share/doc/wanna-build/wanna-build.text.gz

Format: HTML
Index: /usr/share/doc/wanna-build/html/index.html
Files: /usr/share/doc/wanna-build/html/*.html
