CREATE ROLE aba;
CREATE ROLE adsb;
CREATE ROLE aloiret;
CREATE ROLE alpha;
CREATE ROLE amd64;
CREATE ROLE arm;
CREATE ROLE armel;
CREATE ROLE aurel32;
CREATE ROLE buildd_alpha;
CREATE ROLE buildd_amd64;
CREATE ROLE buildd_arm;
CREATE ROLE buildd_armel;
CREATE ROLE buildd_hppa;
CREATE ROLE "buildd_hurd-i386";
CREATE ROLE buildd_i386;
CREATE ROLE buildd_ia64;
CREATE ROLE "buildd_kfreebsd-amd64";
CREATE ROLE "buildd_kfreebsd-i386";
CREATE ROLE buildd_mips;
CREATE ROLE buildd_mipsel;
CREATE ROLE buildd_powerpc;
CREATE ROLE buildd_s390;
CREATE ROLE buildd_sparc;
CREATE ROLE colint;
CREATE ROLE dannf;
CREATE ROLE devin;
CREATE ROLE fs;
CREATE ROLE fw;
CREATE ROLE geissert;
CREATE ROLE guest;
CREATE ROLE he;
CREATE ROLE hppa;
CREATE ROLE "hurd-i386";
CREATE ROLE i386;
CREATE ROLE ia64;
CREATE ROLE iuculano;
CREATE ROLE jcristau;
CREATE ROLE jmm;
CREATE ROLE joey;
CREATE ROLE jwilk;
CREATE ROLE "kfreebsd-amd64";
CREATE ROLE "kfreebsd-i386";
CREATE ROLE kibi;
CREATE ROLE kroeckx;
CREATE ROLE lamont;
CREATE ROLE luk;
CREATE ROLE mbanck;
CREATE ROLE mehdi;
CREATE ROLE mips;
CREATE ROLE mipsel;
CREATE ROLE nion;
CREATE ROLE noahm;
CREATE ROLE nomeata;
CREATE ROLE p2;
CREATE ROLE pkern;
CREATE ROLE postgres;
CREATE ROLE powerpc;
CREATE ROLE riku;
CREATE ROLE s390;
CREATE ROLE seb;
CREATE ROLE sf;
CREATE ROLE sparc;
CREATE ROLE sthibault;
CREATE ROLE thijs;
CREATE ROLE vorlon;
CREATE ROLE waldi;
CREATE ROLE wb_all;
CREATE ROLE wb_security;
CREATE ROLE wbadm;
CREATE ROLE white;
CREATE ROLE wookey;
CREATE ROLE wouter;
CREATE ROLE zobel;
GRANT alpha TO aloiret GRANTED BY wbadm;
GRANT alpha TO buildd_alpha GRANTED BY wbadm;
GRANT alpha TO kibi GRANTED BY wbadm;
GRANT alpha TO vorlon GRANTED BY wbadm;
GRANT alpha TO wb_all GRANTED BY wbadm;
GRANT amd64 TO buildd_amd64 GRANTED BY wbadm;
GRANT amd64 TO fs GRANTED BY wbadm;
GRANT amd64 TO i386 GRANTED BY wbadm;
GRANT amd64 TO kroeckx GRANTED BY wbadm;
GRANT amd64 TO wb_all GRANTED BY wbadm;
GRANT arm TO aurel32 GRANTED BY wbadm;
GRANT arm TO buildd_arm GRANTED BY wbadm;
GRANT arm TO colint GRANTED BY wbadm;
GRANT arm TO riku GRANTED BY wbadm;
GRANT arm TO wb_all GRANTED BY wbadm;
GRANT arm TO wookey GRANTED BY wbadm;
GRANT armel TO arm GRANTED BY wbadm;
GRANT armel TO aurel32 GRANTED BY wbadm;
GRANT armel TO buildd_armel GRANTED BY wbadm;
GRANT armel TO colint GRANTED BY wbadm;
GRANT armel TO riku GRANTED BY wbadm;
GRANT armel TO wb_all GRANTED BY wbadm;
GRANT armel TO wookey GRANTED BY wbadm;
GRANT hppa TO buildd_hppa GRANTED BY wbadm;
GRANT hppa TO dannf GRANTED BY wbadm;
GRANT hppa TO lamont GRANTED BY wbadm;
GRANT hppa TO wb_all GRANTED BY wbadm;
GRANT "hurd-i386" TO "buildd_hurd-i386" GRANTED BY wbadm;
GRANT "hurd-i386" TO mbanck GRANTED BY wbadm;
GRANT "hurd-i386" TO sthibault GRANTED BY wbadm;
GRANT "hurd-i386" TO wb_all GRANTED BY wbadm;
GRANT i386 TO buildd_i386 GRANTED BY wbadm;
GRANT i386 TO kroeckx GRANTED BY wbadm;
GRANT i386 TO luk GRANTED BY wbadm;
GRANT i386 TO pkern GRANTED BY wbadm;
GRANT i386 TO wb_all GRANTED BY wbadm;
GRANT ia64 TO buildd_ia64 GRANTED BY wbadm;
GRANT ia64 TO lamont GRANTED BY wbadm;
GRANT ia64 TO wb_all GRANTED BY wbadm;
GRANT "kfreebsd-amd64" TO aurel32 GRANTED BY wbadm;
GRANT "kfreebsd-amd64" TO "buildd_kfreebsd-amd64" GRANTED BY wbadm;
GRANT "kfreebsd-amd64" TO kibi GRANTED BY wbadm;
GRANT "kfreebsd-amd64" TO wb_all GRANTED BY wbadm;
GRANT "kfreebsd-i386" TO aurel32 GRANTED BY wbadm;
GRANT "kfreebsd-i386" TO "buildd_kfreebsd-i386" GRANTED BY wbadm;
GRANT "kfreebsd-i386" TO kibi GRANTED BY wbadm;
GRANT "kfreebsd-i386" TO wb_all GRANTED BY wbadm;
GRANT mips TO buildd_mips GRANTED BY wbadm;
GRANT mips TO p2 GRANTED BY wbadm;
GRANT mips TO wb_all GRANTED BY wbadm;
GRANT mipsel TO buildd_mipsel GRANTED BY wbadm;
GRANT mipsel TO mips GRANTED BY wbadm;
GRANT mipsel TO wb_all GRANTED BY wbadm;
GRANT mipsel TO zobel GRANTED BY wbadm;
GRANT powerpc TO buildd_powerpc GRANTED BY wbadm;
GRANT powerpc TO pkern GRANTED BY wbadm;
GRANT powerpc TO wb_all GRANTED BY wbadm;
GRANT powerpc TO wouter GRANTED BY wbadm;
GRANT s390 TO buildd_s390 GRANTED BY wbadm;
GRANT s390 TO waldi GRANTED BY wbadm;
GRANT s390 TO wb_all GRANTED BY wbadm;
GRANT sparc TO buildd_sparc GRANTED BY wbadm;
GRANT sparc TO he GRANTED BY wbadm;
GRANT sparc TO kibi GRANTED BY wbadm;
GRANT sparc TO wb_all GRANTED BY wbadm;
GRANT sparc TO zobel GRANTED BY wbadm;
GRANT wb_all TO adsb GRANTED BY wbadm;
GRANT wb_all TO aurel32 GRANTED BY wbadm;
GRANT wb_all TO jcristau GRANTED BY wbadm;
GRANT wb_all TO jwilk GRANTED BY wbadm;
GRANT wb_all TO kibi GRANTED BY wbadm;
GRANT wb_all TO kroeckx GRANTED BY wbadm;
GRANT wb_all TO mehdi GRANTED BY wbadm;
GRANT wb_all TO nomeata GRANTED BY wbadm;
GRANT wb_all TO vorlon GRANTED BY wbadm;
GRANT wb_all TO wbadm GRANTED BY wbadm;
GRANT wb_all TO zobel GRANTED BY wbadm;
GRANT wb_security TO dannf GRANTED BY wbadm;
GRANT wb_security TO devin GRANTED BY wbadm;
GRANT wb_security TO fw GRANTED BY wbadm;
GRANT wb_security TO geissert GRANTED BY wbadm;
GRANT wb_security TO iuculano GRANTED BY wbadm;
GRANT wb_security TO jmm GRANTED BY wbadm;
GRANT wb_security TO joey GRANTED BY wbadm;
GRANT wb_security TO nion GRANTED BY wbadm;
GRANT wb_security TO noahm GRANTED BY wbadm;
GRANT wb_security TO seb GRANTED BY wbadm;
GRANT wb_security TO sf GRANTED BY wbadm;
GRANT wb_security TO thijs GRANTED BY wbadm;
GRANT wb_security TO white GRANTED BY wbadm;
GRANT wbadm TO aba GRANTED BY wbadm;
GRANT wbadm TO he GRANTED BY wbadm;
GRANT wbadm TO kroeckx GRANTED BY wbadm;
GRANT wbadm TO luk GRANTED BY wbadm;
GRANT wbadm TO pkern GRANTED BY wbadm;
